### PR TITLE
support inviting to game over steam friends

### PR DESCRIPTION
**Pull request by hylje**
resolves https://github.com/uspgamedev/luasteam/issues/29

### CODE REVIEW

**Comment by yancouto** [comment]
This looks good. Was this tested in some game, though?

**Comment by hylje** [comment]
Rich presence joining works great on a game lobby that we have tested in practice with my friend that works on his game, the command line parsing function has not been explicitly tested but I keep nagging him about implementing it

**Comment by hylje** [comment]
rebased against latest upstream master

**Review by yancouto — APPROVED** [review]
Ok I'll merge this, after I fix the previous merge shenanigans I did

**Comment by hylje** [comment]
I'll rebase again, sec

**Comment by yancouto** [comment]
Done, I landed this.

BTW I changed the name of the key in the connect callback from `connectString` to `connect`.

I also changed some docs. In the future, try to stick as close as possible to the steam docs, mostly copying and rephrasing them. Also, careful with the trailing whitespaces.

Thank you for the changes!!


Closing as this was merged, though it didn't seem to auto-detect.

**Pull request closed without merging**
