### PR TITLE
Add UGC.subscribeItem and UGC.unsubscribeItem

### PR DESCRIPTION
**Pull request by oatmealine**
Adds implementations for [ISteamUGC.SubscribeItem](https://partner.steamgames.com/doc/api/ISteamUGC#SubscribeItem) and [ISteamUGC.UnsubscribeItem](https://partner.steamgames.com/doc/api/ISteamUGC#UnsubscribeItem) complete with documentation

### CODE REVIEW

**Review by yancouto — APPROVED** [review]
These changes look good. Did you use this on any game to validate them?

**Comment by oatmealine** [comment]
Yep, seems to subscribe/unsubscribe and report back correctly

**Comment by yancouto** [comment]
Are you planning on submitting any other PRs soon or not? (I need to know if I should do a release now or not)

**Comment by oatmealine** [comment]
I'm looking into implementing the query APIs (for querying workshop items, subscribed items, etc.) but I'm not sure if I'm gonna be fully done with that up until much later on

**Pull request merged**
